services:
  postgres:
    image: postgres:16
    container_name: cast-rust-db-postgres
    env_file:
      - path: .env
        required: true
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '${DB_PORT:-5432}:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      retries: 5
      timeout: 3s

  redis:
    build: ./docker/redis
    container_name: cast-rust-redis-cache
    restart: always
    mem_limit: 2.5G
    memswap_limit: 4G
    cpus: 2
    env_file:
      - path: .env
        required: true
    volumes:
      - redis:/data
    ports:
      - ${REDIS_CACHE_PORT:-27002}:6379
    healthcheck:
      test: ['CMD-SHELL', 'redis-cli ping']
      interval: 10s
      retries: 5
      timeout: 3s
  
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: cast-rust-azurite
    restart: unless-stopped
    env_file:
      - path: .env
        required: true
    volumes:
      - azurite-data:/data
    ports:
      - '${AZURE_CAST_RUST_BLOB_PORT:-10000}:10000'
      - '${AZURE_CAST_RUST_QUEUE_PORT:-10001}:10001'
      - '${AZURE_CAST_RUST_TABLE_PORT:-10002}:10002'
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:10000/cast-rust-azurite || exit 1"]
      interval: 10s
      retries: 5
      timeout: 3s

volumes:
  redis:
    driver: local
  postgres:
    driver: local
  azurite-data:
    driver: local
