[tasks.pre-build-all]
description = "Builds all APIs in debug mode before starting."
command = "cargo"
args = ["build", "--workspace"]

[tasks.start-all]
description = "Starts all API services concurrently with colored logs from debug binaries."
dependencies = ["pre-build-all"]
command = "concurrently"
args = [
    "-k",
    "-p",
    "[{name}]",
    "-n",
    "AuthApi,AdminApi,ViewerApi",
    "-c",
    "blue,magenta,red",
    "\"./target/debug/auth_api\"",
    "\"./target/debug/admin_api\"",
    "\"./target/debug/viewer_api\""
]

[tasks.start-auth-api]
description = "Starts the auth_api"
command = "cargo"
args = ["run", "--package", "auth_api"]
detached = true

[tasks.start-admin-api]
description = "Starts the admin_api"
command = "cargo"
args = ["run", "--package", "admin_api"]
detached = true

[tasks.start-viewer-api]
description = "Starts the viewer_api"
command = "cargo"
args = ["run", "--package", "viewer_api"]
detached = true