//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "directors")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub biography: Option<String>,
    pub birth_date: Option<DateTime>,
    pub profile_picture_url: Option<String>,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::video_directors::Entity")]
    VideoDirectors,
}

impl Related<super::video_directors::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::VideoDirectors.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
