//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

pub mod prelude;

pub mod access_groups;
pub mod actors;
pub mod categories;
pub mod directors;
pub mod favorites;
pub mod ratings;
pub mod series;
pub mod users;
pub mod users_access_groups;
pub mod video_actors;
pub mod video_categories;
pub mod video_directors;
pub mod videos;
pub mod watch_history;
