//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

pub use super::access_groups::Entity as AccessGroups;
pub use super::actors::Entity as Actors;
pub use super::categories::Entity as Categories;
pub use super::directors::Entity as Directors;
pub use super::favorites::Entity as Favorites;
pub use super::ratings::Entity as Ratings;
pub use super::series::Entity as Series;
pub use super::users::Entity as Users;
pub use super::users_access_groups::Entity as UsersAccessGroups;
pub use super::video_actors::Entity as VideoActors;
pub use super::video_categories::Entity as VideoCategories;
pub use super::video_directors::Entity as VideoDirectors;
pub use super::videos::Entity as Videos;
pub use super::watch_history::Entity as WatchHistory;
